variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_AUTHS: "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_PATH
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

.test-template: &test
  stage: test
  script:
    - LISP=$LISP make real-check
  except:
    - schedules

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

dependents:
  stage: deploy
  inherit:
    default: false
  script:
    - "curl -X POST -F token=1a461b5961e7d178128c559ff81cdd -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/195/trigger/pipeline" # sel
  only:
    - master
  except:
    - schedules

scheduled-build:
  stage: build
  inherit:
    default: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: ["kubernetes", "cluster"]
  script:
    - echo $DOCKER_AUTHS > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context=$CI_PROJECT_DIR/
      --dockerfile=$CI_PROJECT_DIR/Dockerfile
      --destination=$DOCKER_REGISTRY/$CI_PROJECT_PATH
  only:
    - schedules
