variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_PATH
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

.test-template: &test
  stage: test
  script:
    - LISP=$LISP make check
  except:
    - schedules

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

dependents:
  stage: deploy
  inherit:
    default: false
  script:
    - "curl -X POST -F token=1a461b5961e7d178128c559ff81cdd -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/195/trigger/pipeline" # sel
  only:
    - master
  except:
    - schedules

build-nightly:
  stage: build
  inherit:
    default: false
  script:
    - docker build --no-cache -t $DOCKER_REGISTRY/$CI_PROJECT_PATH .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH
  only:
    - schedules
