variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_AUTHS: "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"

default:
  image: $CI_REGISTRY_IMAGE
  tags: [shared]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

.test-template: &test
  stage: test
  script:
    - LISP=$LISP make real-check
  except:
    - schedules

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

dependents:
  stage: deploy
  trigger: synthesis/sel
  only:
    - master
  except:
    - schedules

scheduled-build:
  stage: build
  inherit:
    default: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: ["kubernetes", "cluster"]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context=$CI_PROJECT_DIR/
      --dockerfile=$CI_PROJECT_DIR/Dockerfile
      --destination=$CI_REGISTRY_IMAGE
  only:
    - schedules
