variables:
  DOCKER_REGISTRY: "docker.grammatech.com"
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build-and-test
  - dependents

.build-template: &build
  script:
    - docker build --build-arg=LISP=${LISP} -f .ci/Dockerfile.${OS} -t ${LOCAL_IMAGE_NAME}-${OS}-${LISP} .
    - docker run -e LISP=${LISP} ${LOCAL_IMAGE_NAME}-${OS}-${LISP} /bin/bash -c "make check";
  after_script:
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}-${LISP}

build-and-test-ubuntu-ccl:
  stage: build-and-test
  variables:
    OS: 'ubuntu'
    LISP: 'ccl'
  <<: *build

build-and-test-ubuntu-sbcl:
  stage: build-and-test
  variables:
    OS: 'ubuntu'
    LISP: 'sbcl'
  <<: *build

build-and-test-arch-ccl:
  stage: build-and-test
  variables:
    OS: 'arch'
    LISP: 'ccl'
  <<: *build

build-and-test-arch-sbcl:
  stage: build-and-test
  variables:
    OS: 'arch'
    LISP: 'sbcl'
  <<: *build

trigger_sel:
  stage: dependents
  script:
    - "curl -X POST -F token=1a461b5961e7d178128c559ff81cdd -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/195/trigger/pipeline"
  only:
    - master
